; ============================================================
; ESTACOES WIFI - AiAgro
; Estacao com WiFi direto (sem LoRa). POST direto pro Supabase + Sheets.
; TEM OTA (tem WiFi).
;
; Compilar:  pio run -e BELA_WIFI_EST1
; Flashar:   pio run -e BELA_WIFI_EST1 -t upload --upload-port /dev/cu.usbserial-XX
; ============================================================

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
    4-20ma/ModbusMaster@^2.0.1
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    bblanchon/ArduinoJson@^7.0.0

; ---------- BELA VISTA WIFI ----------
[env:BELA_WIFI_EST1]
build_flags =
  -DDEVICE_CODIGO=\"BELA_WIFI_EST1\"
  -DORIGEM=\"BELA_WIFI_EST1\"
  -DDISP_ID=\"2f33249c-4c20-4f47-92c5-3989b50408d8\"
  -DWIFI_SSID=\"Ap6401-2G\"
  -DWIFI_PASS=\"21012003\"
